package com.example.merchantadministration.usecase.query

import com.example.merchantadministration.presentation.ItemWithSelectedAttributeIdsParam

interface ItemsWithSelectedAttributesCheckingQuery {
    fun checkItemsWithSelectedAttributes(itemWithSelectedAttributeIdsParams: List<ItemWithSelectedAttributeIdsParam>): Boolean
}