services:
  order_reception_mysql:
    build:
      context: .
    container_name: order_reception_mysql
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_TCP_PORT: 3307
    volumes:
      - order_reception:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./conf.d:/etc/mysql/conf.d/
volumes:
  order_reception: