spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF