services:
  merchant_administration_mysql:
    build:
      context: .
    container_name: merchant_administration_mysql
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_TCP_PORT: 3308
    volumes:
      - merchant_administration:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./conf.d:/etc/mysql/conf.d/
volumes:
  merchant_administration: